/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'NISUM CONSULTING' at '6/10/16 7:28 PM' with Gradle 2.14.1
 *
 * @author NISUM CONSULTING, @date 6/10/16 7:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
